workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: 3.38.9
      java: 17
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
      - name: Rename APK
        script: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/GeoAttendance-release.apk
    publishing:
      email:
        recipients:
          - essilfielawrence489@gmail.com
        notify:
          success: true
          failure: true
